name: gym_smart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-131.0.dev <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  sqlite3: ^2.4.4
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.19.1
flutter:
  assets: 
    - assets/exercises.db
